theme: jekyll-theme-minimal
title: Documentación Nova Cloud
description: Documentación y guías de configuración Microsoft Azure y Microsoft 365 de Nova Cloud. División tecnológica de Condor Comunicaciones.

logo: images/nova-cloud-logo.png
